services:
  app:
    build: .
    container_name: forum-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/forumapp
      - JWT_SECRET=password
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
  
  db:
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forumapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: